### ISSUE TITLE
"Import Music via Wi-Fi" feature is chinese on HibyOS 2.2

### ISSUE THREAD

**Issue by lontrafag** [vext01/hiby-issues#56]
Trying to transfer files via the built-in ftp shows a chinese page.

The issue was not present on HibyOS 2.0.

**Comment by Eridyne** [comment]
Can confirm. 

At least on the R3 Pro, you can work around this by switching language, to any other and then back to your preferred.

It seems like the language for the built in server isn't correctly set on first boot.

**Comment by lontrafag** [comment]
Done your steps and working fine, thank you!
